language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
env:
  - DB=mysql
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq zsh
before_script:
  - "cp config/database.yml.travis.mysql config/database.yml"
  - "RAILS_ENV=test bundle exec rake db:create db:test:load"
script: bundle exec rake test
