#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Worker.backend = :active_record
Delayed::Command.new(ARGV).daemonize
